version: "3.9"
services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "7777:7777"
    environment:
      AGNO_DB_URL: ${AGNO_DB_URL:-sqlite:///./scopex.db}
      AGNO_HOST: ${AGNO_HOST:-0.0.0.0}
      AGNO_PORT: ${AGNO_PORT:-7777}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:3000}
    volumes:
      - ./backend/data:/app/data

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:7777}
